function [image]=lens(focal, photons, working_distance, relative_illumination)
    % lens models the action of a lens on the beamspot light produced by the
    % beam target interaction
    % Inputs:
    %   focal: The focal length of the lens in mm
    %   photons:               A light intensity matrix generated by the target
    %                          function
    %   working_distance:      The distance between the lens and target in mm
    %   relative_illumination: The relative intensity of the light after
    %                          interaction with the lens
    % Outputs:
    %   image: A matrix containing the spatial distribution of light intensity
    %          after refraction occurs


    % TODO: Determine best way to do the ray tracing on the matrix and implement


end