function [photon_mat] = target(beam_mat, tau_fast, tau_slow, photon_conversion)
    % target models the interaction of the electron beam with the target screen
    % This function models the photons emitted from the target screen both
    % spatially and in time. The time resolution matches that of the beam
    % matrix generated at the beginning of the simulation script.
    % Inputs:
    %   beam_mat: A matrix representing the electron beam generated by the beam
    %             function
    %   tau_fast: The fast intensity decay coefficient of the material
    %   tau_slow: The slow intensity decay coefficient of the material
    %   photon_conversion: The photon conversion coefficient of the material
    %                      with units of photons/keV
    % Outputs:
    %   photon_mat: A matrix representing the photons output from the interaction
    %   containing the spatial light intensity distribution

    % TODO: Figure out how the decay time can be properly used

    photon_mat = beam_mat * photon_conversion;

end